# Generated by Django 4.2.13 on 2024-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.IntegerField(default=2500),
            preserve_default=False,
        ),
    ]
